services:
  first-service:
      service-name: hello-world
      address: localhost
      ports:
        - 9000
        - 9001
      requests:
          http:
            GET:
                /hello-world: RR