services:
  first-service:
      service-name: hello-world
      domain: localhost:80
      address: localhost
      ports: 8080...8083
      requests:
        #request type: path
        - get: /hello-world