services:
  first-service:
      service-name: hello-world
      address: localhost
      ports:
        - 8080
        - 8081
      requests:
          http:
            GET:
                /hello-world: RR
                /stop-the-world/{s}: RR
            POST:
