algorithm: RR
load-balancer-address: :8080

services:
  first-service:
    name: hello-world-1
    address: http://localhost:9000
    healthcheck:
      path: /healthcheck
      interval: 1s
      timeout: 2s
      unhealthy-threshold: 2
      timeout-threshold:
  second-service:
    name: hello-world-2
    address: http://localhost:9001
    healthcheck:
      path: /healthcheck
      interval: 1s
      timeout: 2s
      unhealthy-threshold: 2
      timeout-threshold: 2